version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: try
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/uniPay
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db