spring:
  application:
    name: UniPay

  profiles:
    active: dev, local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/uniPay}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop  # ⚠️ Change to 'update' or 'none' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

# Custom application settings
application:
  front-url: ${FRONT_URL:http://localhost:3000}
