spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: anas.abbal10@gmail.com
    password: ecnijepaxsaeccpi
    port: '587'
  sql:
    init:
      mode: always
  application:
    name: UniPay

  profiles:
    active: dev, local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/uniPay}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop  # ⚠️ Change to 'update' or 'none' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: QkZDa0Z3S3dZalZ3YnhNU2h4T2dUYUJ3U2NhVGxLQ3RtU1h3QmFsRVRPbXlXR1pU
  access-token-expiration: 900000    # 15 minutes
  refresh-token-expiration: 604800000 # 7 days
  mfa-challenge-expiration: 300000

# Custom application settings
application:
  front-url: ${FRONT_URL:http://localhost:3000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  website: www.unipay.com
  name: UniPay
  support:
    email: anas.abbal10@gmail.com