spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: anas.abbal10@gmail.com
    password: nblrzrmovgchaxkg
    port: '587'
  sql:
    init:
      mode: always
  application:
    name: UniPay

  profiles:
    active: dev, local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/uniPay}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop  # ⚠️ Change to 'update' or 'none' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: your-256-bit-base64-encoded-secret-key
  access-token-expiration: 900000    # 15 minutes
  refresh-token-expiration: 604800000 # 7 days

# Custom application settings
application:
  front-url: ${FRONT_URL:http://localhost:3000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html


