spring:
  application:
    name: UniPay

  profiles:
    active: dev, local

    #datasource:
    #driver-class-name: org.postgresql.Driver
    #url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/uniPay}
    #username: ${DATABASE_USER:postgres}
    #password: ${DATABASE_PASSWORD:postgres}
    #initialization-mode: never
    #platform: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api
  port: 8080

# application config :
application:
  front-url: ${FRONT_URL:http://localhost:3000}
